### ISSUE TITLE
[Bug]: Add on not working

### ISSUE THREAD

**Issue by chinedu40** [t0bst4r/matterbridge-home-assistant-addon#107]
### What happened?

I'm getting error in the logs and the plugin is not working with the latest update

### Your configuration

included domains: cover

### Relevant log output

```shell
ERROR  InteractionServer    Subscription 3750611146 for Session 31123: Error while sending initial data reports The number NaN cannot be converted to a BigInt because it is not an integer
    at BigInt (<anonymous>)
    at toBigInt (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/util/Number.js:25:38)
    at DataWriter.writeUInt64 (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/util/DataWriter.js:32:54)
    at TlvCodec.writePrimitive (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvCodec.js:312:27)
    at TlvByteArrayWriter.writePrimitive (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvSchema.js:74:14)
    at file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvAny.js:57:18
    at Array.forEach (<anonymous>)
    at AnySchema.encodeTlvInternal (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvAny.js:37:15)
    at file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvArray.js:22:51
    at Array.forEach (<anonymous>)
```

### Version

2.3.1-104

**Comment by t0bst4r** [comment]
This should be fixed since 2.3.3.
Could you please test it and then close this issue if everything is working?
