### ISSUE TITLE
[Bug]: canot add to alexa

### ISSUE THREAD

**Issue by apereipa** [t0bst4r/matterbridge-home-assistant-addon#110]
### What happened?

I can't add matter to Alexa
I have the logs here with the error

info - [18:25:33.930] [Matterbridge]: WebSocketServer client "::ffff:192.168.31.112" connected to Matterbridge
info - [18:25:59.606] [Matterbridge]: Active session changed on fabric 1 id 255242360313260514 vendor 4631 (Alexa) for Matterbridge { name: 'secure/57685', nodeId: 255384247184513152, peerNodeId: 255242360343514913, fabric: { fabricIndex: 1, fabricId: 255242360313260514, nodeId: 255384247184513152, rootNodeId: 18446744060825763882, rootVendorId: 4631, label: '' }, isPeerActive: true, secure: true, lastInteractionTimestamp: 1722878759604, lastActiveTimestamp: 1722878759604, numberOfActiveSubscriptions: 0 }
info - [18:26:01.491] [PluginManager]: Configuring plugin matterbridge-home-assistant type DynamicPlatform
notice - [18:26:01.492] [PluginManager]: Configured plugin matterbridge-home-assistant type DynamicPlatform
info - [18:26:31.547] [Matterbridge]: Setting reachability to true for Matterbridge
info - [18:26:57.112] [Matterbridge]: Saving config for plugin matterbridge-home-assistant...
warn - [18:27:10.128] [Matterbridge]: Commissioning removed from fabric 1 for Matterbridge. Resetting the commissioning server ...
warn - [18:27:10.324] [Matterbridge]: Restart to activate the pairing for Matterbridge.
warn - [18:27:10.926] [Matterbridge]: pairingCodes for /api/settings not found
warn - [18:27:10.930] [Matterbridge]: pairingCodes for /api/settings not found

this is the configuration I have in homeassistant:

include_domains:
  - light
  - switch
include_patterns: []
include_labels: []
include_platforms: []
exclude_domains: []
exclude_patterns: []
exclude_labels: []
exclude_platforms: []
frontend_port: 8283
matter_port: 5540
overrides: |
  {
    "domains": {
    },
    "entities": {
    }
  }

### Version

1.4.1

**Comment by t0bst4r** [comment]
Hey, thanks for reaching out!

1. the log says there is one active session with alexa. So what does "cannot connect" look like?
2. additionally the log says "Restart to activate the pairing for Matterbridge" - did you already restart the addon?
3. if the restart didnt help, could you please open up the web ui, go to settings and click "factory reset" - after that you should get a new provisioning code. its always a good idea to restart the addon between factory-reset and pairing.
4. you are mentioning, that you are using version 1.4.1 - are you sure? we are at `2.5.x` at the moment. Additionally your config does not match the config we had in `1.x`. I assume you are at `>= 2.3`.

**Comment by apereipa** [comment]
In alexa app, i have a error, " error rn002" 

i already tried to restart, when matterbriedg asks, and nothing happens,
a new pairing code is generated

my version is 2.4.0 of matterbridge-home-assistant


info - [20:40:51.417] [Matterbridge]: Active session changed on fabric 1 id 255242360313260514 vendor 4631 (Alexa) for Matterbridge { name: 'secure/38584', nodeId: 255418184805796832, peerNodeId: 255242368052410561, fabric: { fabricIndex: 1, fabricId: 255242360313260514, nodeId: 255418184805796832, rootNodeId: 18446744060825763882, rootVendorId: 4631, label: '' }, isPeerActive: true, secure: true, lastInteractionTimestamp: 1722886851415, lastActiveTimestamp: 1722886851415, numberOfActiveSubscriptions: 0 }
info - [20:41:08.212] [Matterbridge]: Setting reachability to true for Matterbridge
warn - [20:42:01.294] [Matterbridge]: Commissioning removed from fabric 1 for Matterbridge. Resetting the commissioning server ...
warn - [20:42:01.491] [Matterbridge]: Restart to activate the pairing for Matterbridge.
info - [20:42:05.564] [Matterbridge]: SIGTERM received, cleaning up...
info - [20:42:05.566] [PluginManager]: Shutting down plugin matterbridge-home-assistant: Matterbridge is closing: SIGTERM received, cleaning up......
notice - [20:42:05.568] [PluginManager]: Shutdown of plugin matterbridge-home-assistant completed
WebSocket - Disconnected from WebSocket: ws://192.168.31.29:8283
WebSocket - Reconnecting (attempt 1 of 10) to WebSocket: ws://192.168.31.29:8283
WebSocket - Connecting to WebSocket: ws://192.168.31.29:8283
WebSocket - WebSocket error connecting to ws://192.168.31.29:8283
WebSocket - Disconnected from WebSocket: ws://192.168.31.29:8283
WebSocket - Reconnecting (attempt 2 of 10) to WebSocket: ws://192.168.31.29:8283
WebSocket - Connecting to WebSocket: ws://192.168.31.29:8283
WebSocket - Connected to WebSocket: ws://192.168.31.29:8283
info - [20:42:11.716] [Matterbridge]: WebSocketServer client "::ffff:192.168.31.112" connected to Matterbridge
notice - [20:42:12.105] [PluginManager]: Loaded plugin matterbridge-home-assistant type DynamicPlatform (entrypoint /usr/local/lib/node_modules/matterbridge-home-assistant/lib/index.js)
info - [20:42:12.106] [PluginManager]: Starting plugin matterbridge-home-assistant type DynamicPlatform

**Comment by apereipa** [comment]
2024-08-07 12:40:55.154 INFO   MatterDevice         Announce done fabric: 255242360313260514 fabricIndex: 1
2024-08-07 12:40:55.155 INFO   AttributeServer      Set remote value for fabric scoped attribute "acl" to [{"fabricIndex":1,"privilege":5,"authMode":2,"subjects":["18446744060825763882"],"targets":null}]
2024-08-07 12:40:55.156 INFO   LegacyInte~ionServer ACL updated { fabricIndex: 1, privilege: 5, authMode: 2, subjects: [ 18446744060825763882 ], targets: null }
2024-08-07 12:40:55.157 INFO   Operationa~alsServer addNoc success, adminVendorId 4631, caseAdminSubject 18446744060825763882
2024-08-07 12:40:55.434 INFO   CaseServer           Received pairing request from udp://192.168.31.161:5541
[12:40:55.507] [Matterbridge] Active session changed on fabric 1 id 255242360313260514 vendor 4631 (Alexa)  for Matterbridge { name: 'secure/25874', nodeId: 256022178783612080, peerNodeId: 255242367815710513, fabric: { fabricIndex: 1, fabricId: 255242360313260514, nodeId: 256022178783612080, rootNodeId: 18446744060825763882, rootVendorId: 4631, label: '' }, isPeerActive: true, secure: true, lastInteractionTimestamp: 1723030855505, lastActiveTimestamp: 1723030855505, numberOfActiveSubscriptions: 0 } { name: 'secure/25874', nodeId: 256022178783612080, peerNodeId: 255242367815710513, fabric: { fabricIndex: 1, fabricId: 255242360313260514, nodeId: 256022178783612080, rootNodeId: 18446744060825763882, rootVendorId: 4631, label: '' }, isPeerActive: true, secure: true, lastInteractionTimestamp: 1723030855505, lastActiveTimestamp: 1723030855505, numberOfActiveSubscriptions: 0 } 
2024-08-07 12:40:55.507 INFO   CaseServer           session 25874 created with udp://192.168.31.161:5541 for Fabric 038D92D0AD04CCB0(index 1) and PeerNode 038ACD94C948F731
2024-08-07 12:40:55.545 INFO   SessionManager       End insecure session insecure/5342793352538033278
2024-08-07 12:41:01.946 ERROR  InteractionMessenger RetransmissionLimitReachedError
    at MessageExchange.retransmitMessage (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/protocol/MessageExchange.js:276:36)
    at TimerNode.callback (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/protocol/MessageExchange.js:296:20)
    at Timeout._onTimeout (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter-node.js/dist/esm/time/TimeNode.js:50:12)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
2024-08-07 12:41:01.948 ERROR  ExchangeManager      The previous message has not been acked yet, cannot send a new message.
    at MessageExchange.send (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/protocol/MessageExchange.js:184:13)
    at InteractionServerMessenger.send (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/protocol/interaction/InteractionMessenger.js:61:26)
    at InteractionServerMessenger.sendStatus (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/protocol/interaction/InteractionMessenger.js:64:17)
    at InteractionServerMessenger.handleRequest (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/protocol/interaction/InteractionMessenger.js:163:20)
    at async LegacyInteractionServer.onNewExchange (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/protocol/interaction/InteractionServer.js:139:5)
    at async ExchangeManager.onMessage (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/protocol/ExchangeManager.js:173:9)
[12:41:22.226] [Matterbridge] Setting reachability to true for Matterbridge 
2024-08-07 12:42:04.537 INFO   FailsafeContext      Failsafe timer expired, Reset fabric builder.
2024-08-07 12:42:04.556 INFO   SessionManager       End CASE session secure/25874
2024-08-07 12:42:04.557 INFO   MatterDevice         All announcements expired
2024-08-07 12:42:04.569 INFO   SecureSession        Register Session secure/25873 to send a close when exchange is ended.
2024-08-07 12:42:04.690 INFO   SessionManager       End PASE session secure/25873
2024-08-07 12:42:04.802 INFO   CommissioningServer  The device was factory reset and restarted.
[12:42:04.803] [Matterbridge] Commissioning removed from fabric 1 for Matterbridge. Resetting the commissioning server ... 
2024-08-07 12:42:04.948 INFO   MatterDevice         All announcements expired
2024-08-07 12:42:05.002 INFO   CommissioningServer  The device was factory reset and restarted.
[12:42:05.028] [Matterbridge] Restart to activate the pairing for Matterbridge.
