### ISSUE TITLE
Error with last update

### ISSUE THREAD

**Issue by marc3k18** [t0bst4r/matterbridge-home-assistant-addon#46]
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Matterbridge
 Populate your Home Assistant instance as Matter Bridge
-----------------------------------------------------------
 Add-on version: 1.0.6
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.3  (amd64 / generic-x86-64)
 Home Assistant Core: 2024.6.2
 Home Assistant Supervisor: 2024.06.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
#############################
CURRENT CLIENT CONFIGURATION:
{
  "includeDomains": [
    "light",
    "switch"
  ],
  "includePatterns": [
    "light.gv_led_lumiere_ambiance_exterieur",
    "light.sl_lamp*",
    "switch.z2m_p_prise_exterieur"
  ],
  "excludeDomains": [],
  "excludePatterns": []
}
#############################

> matterbridge
> matterbridge -add ./node_modules/matterbridge-home-assistant

[20:04:40.385] [Matterbridge] Created Matterbridge Plugin Directory: /root/Matterbridge 
[20:04:40.391] [Matterbridge] Matterbridge version 1.2.22 mode  running on Linux 6.6.29-haos linux x64 
[20:04:40.396] [Matterbridge] Plugin /app/node_modules/matterbridge-home-assistant/package.json already added to matterbridge 

> matterbridge
> matterbridge -bridge

[20:04:41.658] [Matterbridge] Matterbridge version 1.2.22 mode bridge running on Linux 6.6.29-haos linux x64 
[20:04:41.949] [Matterbridge] Loading plugin matterbridge-home-assistant type DynamicPlatform 
[20:04:41.950] [Matterbridge] WebSocketServer is listening on ws://10.18.0.250:8284 
[20:04:41.950] [Matterbridge] The frontend is listening on http://10.18.0.250:8283 
[20:04:42.013] [Matterbridge] Loaded plugin matterbridge-home-assistant type DynamicPlatform (entrypoint /app/node_modules/matterbridge-home-assistant/lib/index.js) 
[20:04:42.014] [Matterbridge] Starting plugin matterbridge-home-assistant type DynamicPlatform 
[20:04:42.014] [HomeAssistantPlatform] onStart called with reason: Matterbridge is starting 
[20:04:42.062] [Matterbridge] Started plugin matterbridge-home-assistant type DynamicPlatform 
[20:04:42.097] [MatterbridgeDevice] Light-Entity light.groupe_led_fenetres supports level control 
[20:04:42.098] [MatterbridgeDevice] Light-Entity light.groupe_led_fenetres supports color control 
[20:04:42.100] [Matterbridge] Added and registered bridged device (1/1) Groupe LED Fenêtres (MA-onofflight) for plugin matterbridge-home-assistant 
[20:04:42.101] [MatterbridgeDevice] FROM HA: light.groupe_led_fenetres changed brightness to undefined 
file:///app/node_modules/matterbridge-home-assistant/lib/devices/light-device.js:151
            const [hue, saturation] = entity.attributes.hs_color;
                                      ^

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at LightDevice.getHomeAssistantColor (file:///app/node_modules/matterbridge-home-assistant/lib/devices/light-device.js:151:39)
    at LightDevice.updateState (file:///app/node_modules/matterbridge-home-assistant/lib/devices/light-device.js:83:32)
    at HomeAssistantPlatform.updateEntity (file:///app/node_modules/matterbridge-home-assistant/lib/platform.js:70:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HomeAssistantPlatform.updateEntities (file:///app/node_modules/matterbridge-home-assistant/lib/platform.js:45:13)

Node.js v18.20.3
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by t0bst4r** [comment]
Thanks for your feedback. That is the same issue as https://github.com/t0bst4r/matterbridge-home-assistant/issues/69

Let's track it over there.
