### ISSUE TITLE
Addon starts and then stops after error

### ISSUE THREAD

**Issue by squito1** [t0bst4r/matterbridge-home-assistant-addon#65]
## Problem 
I start the Matterbridge addon and it runs for 30 seconds then stops

## Expected behavior
addon to run

## Actual behavior
addon started with errors then stopped

```
-----------------------------------------------------------
 Add-on version: 1.2.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.4  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.6.3
 Home Assistant Supervisor: 2024.06.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
#############################
CURRENT CLIENT CONFIGURATION:
{
  "includeDomains": [],
  "includePatterns": [],
  "excludeDomains": [],
  "excludePatterns": []
}
#############################

> matterbridge
> matterbridge -add ./node_modules/matterbridge-home-assistant

[13:59:09.298] [Matterbridge] Created Matterbridge Plugin Directory: /root/Matterbridge 
[13:59:09.318] [Matterbridge] Matterbridge version 1.3.0 mode  running on Linux 6.6.31-haos-raspi linux arm64 
[13:59:09.333] [Matterbridge] Plugin /app/node_modules/matterbridge-home-assistant/package.json already added to matterbridge 

> matterbridge
> matterbridge -bridge

[13:59:13.177] [Matterbridge] Matterbridge version 1.3.0 mode bridge running on Linux 6.6.31-haos-raspi linux arm64 
[13:59:13.649] [Matterbridge] Loading plugin matterbridge-home-assistant type DynamicPlatform 
[13:59:13.653] [Matterbridge] WebSocketServer is listening on ws://192.168.1.254:8284 
[13:59:13.655] [Matterbridge] The frontend is listening on http://192.168.1.254:8283 
[13:59:13.894] [Matterbridge] Loaded plugin matterbridge-home-assistant type DynamicPlatform (entrypoint /app/node_modules/matterbridge-home-assistant/lib/index.js) 
[13:59:13.895] [Matterbridge] Starting plugin matterbridge-home-assistant type DynamicPlatform 
[13:59:13.896] [HomeAssistantPlatform] onStart called with reason: Matterbridge is starting 
[13:59:14.035] [Matterbridge] Started plugin matterbridge-home-assistant type DynamicPlatform 
[13:59:14.262] [Matterbridge] Added and registered bridged device (1/1) Garage Light Bottom (MA-onofflight) for plugin matterbridge-home-assistant 
[13:59:14.272] [Matterbridge] Added and registered bridged device (2/2) Garage Light Top (MA-onofflight) for plugin matterbridge-home-assistant 
[13:59:14.280] [Matterbridge] Added and registered bridged device (3/3) Lumos (MA-onofflight) for plugin matterbridge-home-assistant 
[13:59:14.301] [Matterbridge] Added and registered bridged device (4/4) Smart Night Light-W (MA-onofflight) for plugin matterbridge-home-assistant 
[13:59:14.312] [Matterbridge] Added and registered bridged device (5/5) Lumos LED (MA-onoffpluginunit) for plugin matterbridge-home-assistant 
[13:59:14.321] [Matterbridge] Added and registered bridged device (6/6) Rachio-3AEE6E Standby (MA-onoffpluginunit) for plugin matterbridge-home-assistant 
[13:59:14.329] [Matterbridge] Added and registered bridged device (7/7) Rachio-3AEE6E Rain delay (MA-onoffpluginunit) for plugin matterbridge-home-assistant 
[13:59:14.337] [Matterbridge] Added and registered bridged device (8/8) Backyard 1 (MA-onoffpluginunit) for plugin matterbridge-home-assistant 
[13:59:14.346] [Matterbridge] Added and registered bridged device (9/9) Backyard 2 (MA-onoffpluginunit) for plugin matterbridge-home-assistant 
[13:59:14.354] [Matterbridge] Added and registered bridged device (10/10) Front Yard North  (MA-onoffpluginunit) for plugin matterbridge-home-assistant 
[13:59:14.361] [Matterbridge] Added and registered bridged device (11/11) Front Yard South (MA-onoffpluginunit) for plugin matterbridge-home-assistant 
[13:59:14.367] [Matterbridge] Added and registered bridged device (12/12) Backyard 3 (MA-onoffpluginunit) for plugin matterbridge-home-assistant 
[13:59:14.374] [Matterbridge] Added and registered bridged device (13/13) Backyard 4 (MA-onoffpluginunit) for plugin matterbridge-home-assistant 
[13:59:14.381] [Matterbridge] Added and registered bridged device (14/14) Weather Adjusting Schedule (MA-onoffpluginunit) for plugin matterbridge-home-assistant 
[13:59:14.387] [Matterbridge] Added and registered bridged device (15/15) G3 Instant Speaker (MA-onoffpluginunit) for plugin matterbridge-home-assistant 
[13:59:14.395] [Matterbridge] Added and registered bridged device (16/16) G3 Instant Status Light On (MA-onoffpluginunit) for plugin matterbridge-home-assistant 
[13:59:14.401] [Matterbridge] Added and registered bridged device (17/17) G3 Instant System Sounds (MA-onoffpluginunit) for plugin matterbridge-home-assistant 
[13:59:14.408] [Matterbridge] Added and registered bridged device (18/18) G3 Instant Overlay: Show Name (MA-onoffpluginunit) for plugin matterbridge-home-assistant 
[13:59:14.416] [Matterbridge] Added and registered bridged device (19/19) G3 Instant Overlay: Show Date (MA-onoffpluginunit) for plugin matterbridge-home-assistant 
[13:59:14.424] [Matterbridge] Added and registered bridged device (20/20) G3 Instant Overlay: Show Logo (MA-onoffpluginunit) for plugin matterbridge-home-assistant 
[13:59:14.432] [Matterbridge] Added and registered bridged device (21/21) G3 Instant Overlay: Show Nerd Mode (MA-onoffpluginunit) for plugin matterbridge-home-assistant 
[13:59:14.440] [Matterbridge] Added and registered bridged device (22/22) G3 Instant Detections: Motion (MA-onoffpluginunit) for plugin matterbridge-home-assistant 
[13:59:14.448] [Matterbridge] Added and registered bridged device (23/23) G3 Instant Privacy Mode (MA-onoffpluginunit) for plugin matterbridge-home-assistant 
[13:59:14.456] [Matterbridge] Added and registered bridged device (24/24) UDM-SE Analytics Enabled (MA-onoffpluginunit) for plugin matterbridge-home-assistant 
[13:59:14.464] [Matterbridge] Added and registered bridged device (25/25) UDM-SE Insights Enabled (MA-onoffpluginunit) for plugin matterbridge-home-assistant 
[13:59:14.473] [Matterbridge] Added and registered bridged device (26/26) AdGuard Home Protection (MA-onoffpluginunit) for plugin matterbridge-home-assistant 
[13:59:14.481] [Matterbridge] Added and registered bridged device (27/27) Apple HomePod Mini (MA-onoffpluginunit) for plugin matterbridge-home-assistant 
[13:59:14.489] [Matterbridge] Added and registered bridged device (28/28) Garage Door 4AFF48 ratgdo (MA-onofflight) for plugin matterbridge-home-assistant 
[13:59:14.497] [Matterbridge] Added and registered bridged device (29/29) Ecobee Smart Sensor (MA-heatcool) for plugin matterbridge-home-assistant 
file:///app/node_modules/@project-chip/matter.js/dist/esm/cluster/server/ClusterServer.js:261
          throw new ImplementationError(
                ^

ImplementationError: Attribute minLevel is optional and not initialized. To use it please initialize it first.
    at ClusterServer.result.<computed> [as setMinLevelAttribute] (file:///app/node_modules/@project-chip/matter.js/dist/esm/cluster/server/ClusterServer.js:261:17)
    at LevelControlAspect.update (file:///app/node_modules/matterbridge-home-assistant/lib/devices/aspects/level-control-aspect.js:34:39)
    at ClimateDevice.updateState (file:///app/node_modules/matterbridge-home-assistant/lib/devices/home-assistant-device.js:21:26)
    at async HomeAssistantMatterAdapter.create (file:///app/node_modules/matterbridge-home-assistant/lib/home-assistant/home-assistant-matter-adapter.js:88:9)
    at async HomeAssistantMatterAdapter.expensiveUpdate (file:///app/node_modules/matterbridge-home-assistant/lib/home-assistant/home-assistant-matter-adapter.js:42:13)
    at async HomeAssistantClient.expensiveUpdate (file:///app/node_modules/matterbridge-home-assistant/lib/home-assistant/home-assistant-client.js:50:13)

Node.js v18.20.3
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

## Steps to reproduce
I uninstalled, restarted, installed, started and the issue repeated.

**Comment by t0bst4r** [comment]
this is related to a bug with climate devices. Please exclude the climate domain in the addinn config and try again. This bug is tracked there: https://github.com/t0bst4r/matterbridge-home-assistant/issues/47

I’ll keep this issue open for others coming here.

**Comment by squito1** [comment]
It worked for about a minute with the exclusion then the the error repopulated and stopped the addon again with the same error.

**Comment by t0bst4r** [comment]
I’ve disabled the broken climate device type until it works.
