### ISSUE TITLE
[Bug]: Home Assistant Ad on does not start after update

### ISSUE THREAD

**Issue by selzilla** [t0bst4r/matterbridge-home-assistant-addon#83]
### What happened?

A bug happened!### 
Home Assistant Ad on does not start after update

### Your configuration

Matterbridge
[Informationen](http://192.168.1.14:8123/hassio/addon/a1b84aa7_matterbridge/info)
[Konfiguration](http://192.168.1.14:8123/hassio/addon/a1b84aa7_matterbridge/config)
[Protokoll](http://192.168.1.14:8123/hassio/addon/a1b84aa7_matterbridge/logs)
Matterbridge
  "excludeDomains": [],
  "excludePatterns": []
}
#############################
[07:54:33.362] [Matterbridge] Created Matterbridge Plugin Directory: /root/Matterbridge 
[07:54:33.383] [Matterbridge] Matterbridge version 1.3.6 mode  running on Linux 6.6.31-haos-raspi linux arm64 
[07:54:33.399] [Matterbridge] Plugin /usr/local/lib/node_modules/matterbridge-home-assistant/package.json already added to matterbridge 
[07:54:36.684] [Matterbridge] Matterbridge version 1.3.6 mode bridge restart mode docker running on Linux 6.6.31-haos-raspi linux arm64 
[07:54:36.706] [Matterbridge] Storage initialize() error! The file .matterbridge/matterbridge.json may be corrupted. 
[07:54:36.708] [Matterbridge] Please delete it and rename matterbridge.backup.json to matterbridge.json and try to restart Matterbridge. 
[07:54:36.710] [Matterbridge] Storage initialize() error! 
[07:54:36.712] [Matterbridge] Shutting down plugin matterbridge-home-assistant 
[07:54:36.714] [Matterbridge] Plugin matterbridge-home-assistant platform not found 
file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/storage/StorageManager.js:30
    if (!this.initialized) throw new StorageError("The storage needs to be initialized first!");
                                 ^

StorageError: The storage needs to be initialized first!
    at StorageManager.createContext (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/storage/StorageManager.js:30:34)
    at Matterbridge.createCommissioningServerContext (file:///usr/local/lib/node_modules/matterbridge/dist/matterbridge.js:1890:52)
    at Matterbridge.parseCommandLine (file:///usr/local/lib/node_modules/matterbridge/dist/matterbridge.js:452:47)

Node.js v18.20.3
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Matterbridge
 Populate your Home Assistant instance as Matter Bridge
-----------------------------------------------------------
 Add-on version: 1.3.6-69
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.4  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.6.4
 Home Assistant Supervisor: 2024.06.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
#############################
CURRENT CLIENT CONFIGURATION:
{
  "includeDomains": [],
  "includePatterns": [],
  "excludeDomains": [],
  "excludePatterns": []

### Version

1.3.6-69

**Comment by t0bst4r** [comment]
This already happened before and I don’t know why actually. 
it is somehow related to Matterbridge…

could you try this?
https://github.com/t0bst4r/matterbridge-home-assistant-addon/issues/59#issuecomment-2183898145

**Comment by selzilla** [comment]
I have tried. I do not have this entry.

**Comment by t0bst4r** [comment]
What entry do you not have? Have a look at the next two comments after the linked one.

**Comment by selzilla** [comment]
I can't find the entry to delete. Even when I am at the top level, the entry does not appear.
/addon_configs/a1b84aa7_matterbridge/storage/.matterbridge/.
I have now deleted the Ads on. Too bad.
